# Generated by Django 4.0 on 2021-12-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_house_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimage',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.houseimage'),
        ),
    ]
