# Generated by Django 4.0 on 2021-12-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_houseimage_house_house_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ManyToManyField(default='', to='api.HouseImage'),
        ),
    ]
