# Generated by Django 4.0 on 2021-12-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_house_images_house_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
        migrations.AddField(
            model_name='houseimage',
            name='house_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.house'),
        ),
    ]
