# Generated by Django 4.0 on 2021-12-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_house_images_houseimage_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='houses/'),
        ),
    ]
