# Generated by Django 4.0 on 2021-12-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_houseimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(null=True, upload_to='houses/'),
        ),
    ]
