# Generated by Django 4.0 on 2021-12-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_houseimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('DO', 'Done')], default='PE', max_length=2)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
    ]
