# Generated by Django 4.0 on 2021-12-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
