# Generated by Django 4.0 on 2021-12-31 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house'),
        ),
    ]
