# Generated by Django 4.0 on 2021-12-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_request_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_pice',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=7),
            preserve_default=False,
        ),
    ]
