# Generated by Django 4.0 on 2022-01-02 01:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=(256, 256), upload_to=''),
        ),
    ]
