# Generated by Django 4.0 on 2022-01-03 13:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
