# Generated by Django 4.0 on 2022-01-03 13:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
