# Generated by Django 4.0 on 2022-01-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_houseimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to='houses/'),
        ),
    ]
